

spring:
  application:
    name: IventoryControl-API
  datasource:
    url: jdbc:postgresql://localhost:5432/iventorydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

springdoc:
  override-with-generic-response: false
